title: Gorkem Bayar
remote_theme: pages-themes/minimal@v0.2.0
logo: /headshot_circle.png
#show_downloads: true
#github:
#  zip_url: https://drive.google.com/file/d/1-_Me4VcVkFkSShjbeIgE5B0eR7RQbY9-/view